#!/usr/bin/env bash
# Generated by apply.sh Thu Jul 30 16:14:24 PDT 2026
# EDIT the REMOTE path below to match this project on the cluster.
set -uo pipefail
REMOTE="tdlong@hpc3.rcic.uci.edu:/dfs7/adl/tdlong/XQTL2-dev"
LOCAL="/Volumes/Raw_store/projects/XQTL2-dev"
CTL="$HOME/.ssh/cm-XQTL2-dev-%C"
RSH="ssh -o ControlMaster=auto -o ControlPath=$CTL -o ControlPersist=600"

case "${1:-}" in
  pull)
  rsync -av -e "$RSH" "$REMOTE/process/" "$LOCAL/process/"
    ;;
  push)
    echo "TODO: fill in push rsync commands"
    exit 1
    ;;
  *) echo "usage: bash sync.sh push|pull"; exit 1;;
esac
